# Generated by Django 2.1.5 on 2019-03-02 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import image_cropping.fields


class Migration(migrations.Migration):
    replaces = [
        ("jobs", "0001_squashed_0012_auto_20151106_1921"),
        ("jobs", "0002_auto_20170920_1310"),
        ("jobs", "0003_auto_20170920_1429"),
        ("jobs", "0004_auto_20171006_1218"),
        ("jobs", "0005_move_fields_from_news"),
        ("jobs", "0006_auto_20171006_1559"),
        ("jobs", "0007_auto_20171006_1713"),
        ("jobs", "0008_auto_20171017_0111"),
    ]

    initial = True

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Bilder som er større enn 770x300 px ser best ut. Du kan beskjære bildet etter opplasting.",
                        null=True,
                        upload_to="uploads/news_pictures",
                        verbose_name="Bilde",
                    ),
                ),
                (
                    "cropping",
                    image_cropping.fields.ImageRatioField(
                        "picture",
                        "770x300",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=False,
                        verbose_name="Beskjæring",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                ("website", models.URLField(blank=True, verbose_name="Nettside")),
                ("name", models.CharField(max_length=200, verbose_name="navn")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="beskrivelse"),
                ),
            ],
            options={
                "verbose_name_plural": "bedrifter",
                "verbose_name": "bedrift",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="RelevantForChoices",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "studieretning",
                    models.CharField(
                        help_text='Mulige valg for "relevant for" når man legger til stillingsannonser.',
                        max_length=50,
                        verbose_name="Valg",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": 'Mulige valg for "relevant for"',
                "verbose_name": 'Mulig valg for "relevant for"',
            },
        ),
        migrations.CreateModel(
            name="TagChoices",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="Tags for stillingsannonsen. Eksempler: deltid, sommerjobb, fulltid, utlandet, by. Søkbar.",
                        max_length=100,
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tags",
                "verbose_name": "Tag",
                "ordering": ("tag",),
            },
        ),
        migrations.CreateModel(
            name="YearChoices",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Klasse: 1, 2, 3, 4 og 5", verbose_name="Klasse"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Klasser",
                "verbose_name": "Klasse",
                "permissions": (("can_see_static_models", "Can see static models"),),
            },
        ),
        migrations.CreateModel(
            name="Advert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deadline_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Søknadsfrist",
                        null=True,
                        verbose_name="Frist",
                    ),
                ),
                (
                    "removal_date",
                    models.DateTimeField(
                        help_text="Når annonsen fjernes fra listen, f.eks. samtidig som søknadsfristen",
                        verbose_name="Forsvinner",
                    ),
                ),
                (
                    "info_file",
                    models.FileField(
                        blank=True,
                        help_text="Informasjon om stillingen",
                        upload_to="stillinger",
                        verbose_name="Informasjonsfil",
                    ),
                ),
                (
                    "info_website",
                    models.URLField(
                        blank=True,
                        help_text="Nettside der man kan søke på stillingen eller få mer informasjon",
                        max_length=150,
                        verbose_name="Infoside",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Hvilken bedrift stillingen er hos",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.Company",
                        verbose_name="Bedrift",
                    ),
                ),
                (
                    "relevant_for_group",
                    models.ManyToManyField(
                        help_text="Hvilke studieretninger stillingsannonsen er relevant for.",
                        to="jobs.RelevantForChoices",
                        verbose_name="Studieretning",
                    ),
                ),
                (
                    "relevant_for_year",
                    models.ManyToManyField(
                        help_text="Hvilke årskull stillingsannonsen er relevant for.",
                        to="jobs.YearChoices",
                        verbose_name="Årskull",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="F.eks. sommerjobb, bergen, kirkenes, olje, konsultering...",
                        to="jobs.TagChoices",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text='Vises kun i artikkelen. Man kan her bruke <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">markdown</a> for å formatere teksten.',
                        verbose_name="brødtekst",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advert_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opprettet av",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Publiseringsdato"
                    ),
                ),
                (
                    "headline",
                    models.CharField(blank=True, max_length=100, verbose_name="tittel"),
                ),
                (
                    "last_changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advert_edited",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Endret av",
                    ),
                ),
                (
                    "last_changed_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Redigeringsdato"
                    ),
                ),
                (
                    "lead_paragraph",
                    models.TextField(
                        blank=True,
                        help_text="Vises på forsiden og i artikkelen",
                        verbose_name="ingress",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "stillingsannonser",
                "verbose_name": "stillingsannonse",
                "ordering": ("-created_date", "headline"),
            },
        ),
    ]
