# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_squashed_0012_auto_20151106_1921"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="allow_comments",
        ),
        migrations.RemoveField(
            model_name="company",
            name="content_type",
        ),
    ]
