# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_move_fields_from_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="news_ptr",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.RenameField(model_name="advert", old_name="news_ptr", new_name="id"),
    ]
