# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_auto_20171006_1559"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advert",
            name="cropping",
        ),
        migrations.RemoveField(
            model_name="advert",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="advert",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="advert",
            name="published",
        ),
        migrations.RemoveField(
            model_name="advert",
            name="view_counter",
        ),
    ]
