# Generated by Django 2.1.5 on 2019-02-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20171017_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='relevant_for_year',
        ),
    ]
