# Generated by Django 2.1.5 on 2019-02-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_advert_relevant_for_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='relevant_for_group',
        ),
        migrations.AddField(
            model_name='advert',
            name='relevant_for_year',
            field=models.ManyToManyField(help_text='Hvilke årskull stillingsannonsen er relevant for.', to='jobs.YearChoices', verbose_name='Årskull'),
        ),
    ]
