# Generated by Django 2.1.5 on 2019-03-11 19:49

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20190218_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='tags',
        ),
        migrations.AlterField(
            model_name='company',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '770x300', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Beskjæring'),
        ),
    ]
