# Generated by Django 2.1.7 on 2019-03-19 20:43

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_advert_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='Bilder som er større enn 770x300 px ser best ut. Du kan beskjære bildet etter opplasting.', null=True, upload_to='uploads/news_pictures', verbose_name='Bilde'),
        ),
    ]
