# Generated by Django 2.1.7 on 2019-03-25 20:09

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20190319_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '770x770', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Beskjæring'),
        ),
    ]
