# Generated by Django 2.1.7 on 2019-03-25 22:02

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20190325_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cropBool',
            field=models.BooleanField(default=False, verbose_name='Crop?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '770x300', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Beskjæring'),
        ),
    ]
