# Generated by Django 2.1.7 on 2019-03-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20190325_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cropBool',
        ),
        migrations.AddField(
            model_name='company',
            name='ignoreCrop',
            field=models.BooleanField(blank=True, default=False, help_text='Beskjæringen vil bli ignorert og bildet vises i full størrelse.', verbose_name='Vis i full størrelse'),
        ),
    ]
