# Generated by Django 2.1.7 on 2019-03-25 22:43

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20190325_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='relevant_for_group',
            field=models.ManyToManyField(help_text='Hvilke studieretninger stillingsannonsen er relevant for.', to='jobs.RelevantForChoices', verbose_name='Studieretning'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '770x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Beskjæring'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ignoreCrop',
            field=models.BooleanField(blank=True, default=False, help_text='Beskjæringen vil bli ignorert og bildet vises i originalt format, med hvit bakgrunn', verbose_name='Vis i full størrelse'),
        ),
    ]
