# Generated by Django 2.1.7 on 2019-03-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20190325_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=models.ImageField(blank=True, help_text='Bilder som er større enn 770x300 px ser best ut. Du kan beskjære bildet etter opplasting.', null=True, upload_to='uploads/news_pictures', verbose_name='Bilde'),
        ),
    ]
