# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="allow_comments",),
    ]
