# Generated by Django 2.1.5 on 2019-02-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_20170920_1255_remove_allow_comments"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="view_counter",),
    ]
