# Generated by Django 3.1.14 on 2022-07-02 13:15

import django.db.models.deletion
from django.db import migrations

import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0005_auto_20200630_2211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Bildealbum som dette albumet hører til. Album er relaterte med en trestruktur.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="album.album",
                verbose_name="Forelder",
            ),
        ),
    ]
