# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 23:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_to_new_meetingrecords(apps, schema_editor):
    Old = apps.get_model('meeting_records', 'MeetingRecordOld')
    New = apps.get_model('meeting_records', 'MeetingRecord')
    for old in Old.objects.all():
        new = New()
        new.id = old.id
        new.title = old.headline
        new.slug = old.slug
        new.description = old.lead_paragraph
        new.pub_date = old.pub_date
        new.file = old.file
        new.created_by = old.created_by
        new.last_changed_by = old.last_changed_by
        new.save()
        new.created_date = old.created_date
        new.last_changed_date = old.last_changed_date
        new.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting_records', '0002_auto_20150811_1047'),
    ]

    operations = [
        migrations.RenameModel(old_name="MeetingRecord", new_name="MeetingRecordOld"),
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publiseringsdato')),
                ('last_changed_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Redigeringsdato')),
                ('title', models.CharField(max_length=100, verbose_name='tittel')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivelse')),
                ('pub_date', models.DateField(default=datetime.date.today, help_text='Publikasjonsdato', null=True, verbose_name='publisert')),
                ('file', models.FileField(help_text='Filnavn', null=True, upload_to='meeting_records', verbose_name='PDF-fil')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetingrecord_created', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av')),
                ('last_changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetingrecord_edited', to=settings.AUTH_USER_MODEL, verbose_name='Endret av')),
                ('slug', models.SlugField(null=True, blank=True, help_text="Denne teksten vises i adressen til siden, og trengs vanligvis ikke å endres")),
            ],
            options={
                'verbose_name_plural': 'Møtereferater',
                'verbose_name': 'Møtereferat',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.RunPython(move_to_new_meetingrecords),
        migrations.DeleteModel(name="MeetingRecordOld"),
    ]
