# Generated by Django 2.1.9 on 2019-09-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20190205_1300'),
        ('exchange', '0002_auto_20161213_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeNewsArticle',
            fields=[
                ('newsarticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.NewsArticle')),
                ('field', models.TextField(blank=True, verbose_name='hhaha')),
            ],
            options={
                'abstract': False,
            },
            bases=('news.newsarticle',),
        ),
    ]
