# Generated by Django 3.0.7 on 2020-10-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0003_exchangenewsarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="annet",
            field=models.TextField(blank=True, help_text="Annet.", null=True),
        ),
        migrations.AddField(
            model_name="exchange",
            name="facebook",
            field=models.CharField(
                blank=True,
                help_text="Link til din facebookprofil (valgfritt).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exchange",
            name="fag",
            field=models.TextField(blank=True, help_text="Fag du tok.", null=True),
        ),
        migrations.AddField(
            model_name="university",
            name="by",
            field=models.CharField(
                default="",
                help_text="Byen universitetet ligger i",
                max_length=30,
                verbose_name="by",
            ),
        ),
    ]
