# Generated by Django 2.1.9 on 2019-09-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_exchangenewsarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangenewsarticle',
            name='field',
        ),
    ]
