# Generated by Django 3.0.7 on 2020-10-23 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0004_auto_20201021_2154"),
        ("exchange", "0005_auto_20201021_2111"),
    ]

    operations = []
