# Generated by Django 3.0.7 on 2021-03-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0006_merge_20201023_1226"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchange",
            name="fag",
        ),
        migrations.AddField(
            model_name="exchange",
            name="optional_email",
            field=models.CharField(
                blank=True,
                help_text="Alternativ epost, la stå blank for å bruke studmail.",
                max_length=100,
                null=True,
                verbose_name="Alternativ epost",
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Emnekode")),
                ("name", models.CharField(max_length=50, verbose_name="Emnenavn")),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange.Exchange",
                    ),
                ),
            ],
        ),
    ]
