# Generated by Django 3.0.7 on 2021-03-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_merge_20201023_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='fag',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Emnekode')),
                ('name', models.CharField(max_length=50, verbose_name='Emnenavn')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Exchange')),
            ],
        ),
    ]
