# Generated by Django 3.0.7 on 2020-11-04 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0007_auto_20201104_1946"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchange",
            name="fag",
        ),
        migrations.AddField(
            model_name="subject",
            name="exchange",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exchange.Exchange",
            ),
        ),
    ]
