# Generated by Django 3.0.7 on 2020-11-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0009_auto_20201104_2105"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="optional_email",
            field=models.CharField(
                blank=True,
                help_text="Alternativ epost, la stå blank for å bruke studmail.",
                max_length=100,
                null=True,
                verbose_name="Alternativ epost",
            ),
        ),
    ]
