# Generated by Django 3.2.22 on 2024-01-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailfeed', '0002_auto_20240109_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailfeed',
            options={'permissions': [('generate_mailfeeds', 'can generate mailfeeds')]},
        ),
    ]
