# Generated by Django 3.1.13 on 2021-10-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0002_poll_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="randomise",
            field=models.BooleanField(
                default=True, verbose_name="Tilfeldig rekkefølge på valg?"
            ),
        ),
    ]
