# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-02 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0018_auto_20151212_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventdoor',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='content_type',
        ),
    ]
