# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-30 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20190130_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='is_display_image',
            field=models.BooleanField(default=False, help_text='Bildet som vises i listen over album', verbose_name='Er visningbilde'),
        ),
    ]
