# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 14:15
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.migrations.operations.special import RunPython


def create_filenames(apps, schema_editor):
    Nablad = apps.get_model("nabladet", "Nablad")
    db_alias = schema_editor.connection.alias
    all_nablad = Nablad.objects.using(db_alias).all()
    for blad in all_nablad:
        blad.filename = blad.file.name
        blad.save()


class Migration(migrations.Migration):

    dependencies = [
        ("nabladet", "0008_remove_nablad_view_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="nablad",
            name="filename",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.RunPython(create_filenames, RunPython.noop),
    ]
