# Generated by Django 2.1.5 on 2019-04-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabladet', '0010_nablad_file_nsfw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nablad',
            name='file',
            field=models.FileField(help_text="Filnavn. OBS: opplasting kan ta rundt ett minutt, så bare trykk 'Lagre' én gang.", upload_to='nabladet', verbose_name='PDF-fil'),
        ),
    ]
