# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nablaweb', '0002_auto_20160921_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaloptions',
            name='main_story_content_type',
        ),
        migrations.RemoveField(
            model_name='generaloptions',
            name='site',
        ),
        migrations.DeleteModel(
            name='GeneralOptions',
        ),
    ]
