# Generated by Django 2.1.9 on 2019-10-03 13:27

from django.db import migrations, models

import image_cropping.fields


class Migration(migrations.Migration):
    dependencies = [
        ("com", "0004_compage_is_interest_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="compage",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "picture",
                "770x300",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="Beskjæring",
            ),
        ),
        migrations.AddField(
            model_name="compage",
            name="picture",
            field=models.ImageField(
                blank=True,
                help_text="Bilder som er større enn 770x300 px ser best ut. Du kan beskjære bildet etter opplasting.",
                null=True,
                upload_to="uploads/news_pictures",
                verbose_name="Bilde",
            ),
        ),
    ]
