# Generated by Django 3.0.7 on 2020-11-11 20:46

from django.db import migrations

import ckeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("com", "0007_auto_20191003_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compage",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Teksten på komitésiden",
                verbose_name="Beskrivelse",
            ),
        ),
    ]
