# Generated by Django 3.2.25 on 2026-02-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("com", "0008_auto_20201111_2046"),
    ]

    operations = [
        migrations.AddField(
            model_name="compage",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Er komitéen aktiv?", verbose_name="Aktiv"
            ),
        ),
    ]
