# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20181122_2012"),
        ("accounts", "0002_auto_20181122_1957"),
    ]

    operations = []
