# Generated by Django 3.1.7 on 2021-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_auto_20200827_1523"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nablauser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
