# Generated by Django 3.2.25 on 2026-08-10 21:33

import django.db.models.deletion
from django.db import migrations, models

import nablapps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_nablauser_darkmode"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrequest",
            name="fysmat_class",
            field=models.ForeignKey(
                default=nablapps.accounts.models.RegistrationRequest.get_newest_class,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.fysmatclass",
            ),
        ),
        migrations.AlterField(
            model_name="fysmatclass",
            name="starting_year",
            field=models.CharField(
                max_length=4, null=True, unique=True, verbose_name="År startet"
            ),
        ),
    ]
