# Generated by Django 3.2.25 on 2026-07-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_registrationrequest_fysmat_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fysmatclass",
            name="starting_year",
            field=models.CharField(
                max_length=4, null=True, unique=True, verbose_name="År startet"
            ),
        ),
    ]
