# Generated by Django 3.2.25 on 2026-07-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_fysmatclass_starting_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentStatus",
            fields=[],
            options={
                "verbose_name": "Kontingentregistrering",
                "verbose_name_plural": "Kontingentregistreringer",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.registrationrequest",),
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="paid",
            field=models.BooleanField(
                default=False, verbose_name="Betalt medlemskontingent"
            ),
        ),
    ]
