# Generated by Django 3.2.25 on 2026-08-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_auto_20260731_1557"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentstatus",
            options={
                "default_permissions": ("change", "view"),
                "verbose_name": "Kontingentregistrering",
                "verbose_name_plural": "Kontingentregistreringer",
            },
        ),
    ]
