# Generated by Django 2.1.13 on 2019-10-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nablaforum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='text_body',
            new_name='text',
        ),
    ]
