# Generated by Django 2.1.13 on 2019-10-19 22:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nablaforum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2019, 10, 19, 22, 16, 15, 299300),
                editable=False,
            ),
            preserve_default=False,
        ),
    ]
