# Generated by Django 2.1.13 on 2019-10-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nablaforum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
