# Generated by Django 2.1.13 on 2019-10-18 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nablaforum', '0002_auto_20191018_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='has_unreads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by_user',
            field=models.ManyToManyField(related_name='read_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='has_unreads',
            field=models.BooleanField(default=False),
        ),
    ]
