# Generated by Django 2.1.13 on 2019-12-25 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nablaforum", "0003_auto_20191025_2140"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
    ]
