# Generated by Django 2.1.13 on 2019-10-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nablaforum', '0003_auto_20191018_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_feed',
            field=models.BooleanField(default=False),
        ),
    ]
