# Generated by Django 2.1.13 on 2020-01-04 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nablaforum', '0004_thread_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='is_pinned',
            new_name='is_class',
        ),
        migrations.AlterField(
            model_name='thread',
            name='threadstarter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
