# Generated by Django 2.1.13 on 2020-05-17 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nablaforum", "0006_auto_20200114_1954"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={
                "permissions": [
                    ("can_post_in_nablafeed", "Can post thread in nablafeed")
                ]
            },
        ),
    ]
