# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0001_squashed_0022_adventdoor_user_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adventdoor",
            name="view_counter",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="view_counter",
        ),
        migrations.RemoveField(
            model_name="test",
            name="view_counter",
        ),
    ]
