# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0001_squashed_0022_adventdoor_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventdoor',
            name='edit_listeners',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='edit_listeners',
        ),
        migrations.RemoveField(
            model_name='test',
            name='edit_listeners',
        ),
    ]
