# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-21 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0003_adventcalendar_requires_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=200)),
                ('correct_output', models.TextField()),
            ],
        ),
    ]
