# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0004_codetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGolfResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.CodeTask')),
            ],
        ),
    ]
