# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-22 19:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0005_codegolfresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("length", models.IntegerField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="result",
                        to="interactive.CodeTask",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="codegolfresult", name="task",),
        migrations.DeleteModel(name="CodeGolfResult",),
    ]
