# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 03:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0007_codegolf_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="result",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
