# Generated by Django 2.1.5 on 2019-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0008_auto_20190104_0304"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="publication_date",
        ),
        migrations.AlterField(
            model_name="test",
            name="published",
            field=models.NullBooleanField(default=True, verbose_name="Publisert"),
        ),
    ]
