# Generated by Django 2.1.13 on 2019-12-01 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0013_santa_santacount"),
        ("interactive", "0013_colorchoice"),
    ]

    operations = []
