# Generated by Django 2.1.9 on 2019-11-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0013_santacount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santacount',
            name='santas',
            field=models.CharField(default='', max_length=24),
        ),
    ]
