# Generated by Django 2.1.13 on 2020-02-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0015_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="placegrid",
            name="uncertainty",
            field=models.BooleanField(
                default=False,
                help_text="Brukere vil kunne velge mellom å plassere raskt og å plassere sikkert.",
                verbose_name="Uskarphet i posisjon og tid og farge",
            ),
        ),
    ]
