# Generated by Django 3.1.13 on 2021-10-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0018_auto_20210909_2046"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField(help_text="Bruk helst 10, 20, 30 osv.")),
                ("title", models.TextField()),
                ("url", models.TextField()),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Bruk samme størrelse på alle bilder, helst 770x300 px",
                        null=True,
                        upload_to="uploads/game_pictures",
                        verbose_name="Bilde",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
    ]
