# Generated by Django 3.1.14 on 2022-04-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0024_result_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="result",
            name="python_version",
            field=models.CharField(max_length=15),
        ),
    ]
