# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_news_ptr_to_id_20171006_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="last_changed_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Redigeringsdato"
            ),
        ),
    ]
