# Generated by Django 2.1.13 on 2020-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190204_2011'),
        ('events', '0005_20191018_modify_open_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_required', models.BooleanField(default=False, verbose_name='påmelding')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='påmeldingsfrist')),
                ('registration_start', models.DateTimeField(blank=True, null=True, verbose_name='påmelding åpner')),
                ('deregistration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='avmeldingsfrist')),
                ('places', models.PositiveIntegerField(blank=True, null=True, verbose_name='antall plasser')),
                ('has_queue', models.NullBooleanField(help_text='Om ventelisten er på, vil det være mulig å melde seg på selv om arrangementet er fullt. De som er i ventelisten vil automatisk bli påmeldt etter hvert som plasser blir ledige.', verbose_name='har venteliste')),
                ('open_for', models.ManyToManyField(blank=True, help_text='Hvilke grupper som får lov til å melde seg på arrangementet. Hvis ingen grupper er valgt er det åpent for alle.', to='accounts.FysmatClass', verbose_name='Åpen for')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='deregistration_deadline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_queue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='open_for',
        ),
        migrations.RemoveField(
            model_name='event',
            name='places',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_required',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_start',
        ),
        migrations.AddField(
            model_name='event',
            name='registration_info_collection',
            field=models.ManyToManyField(to='events.RegistrationInfo'),
        ),
    ]
