# Generated by Django 3.0.7 on 2020-06-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_20191018_modify_open_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="penalty",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Prikk"
            ),
        ),
    ]
