# Generated by Django 2.1.13 on 2020-08-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200820_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationinfo',
            name='registration_required',
        ),
    ]
