# Generated by Django 3.0.7 on 2020-09-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventregistration_attendance_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
    ]
