# Generated by Django 3.0.7 on 2020-10-21 21:54

from django.db import migrations

import ckeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_auto_20200909_1636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="brødtekst"),
        ),
    ]
