# Generated by Django 3.2.25 on 2024-09-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_auto_20220702_1315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
