# Generated by Django 3.0.7 on 2021-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
