# Generated by Django 3.0.7 on 2021-02-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_auto_20210203_1912"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="votingevent",
            options={
                "permissions": [
                    ("vote_admin", "can administer voting"),
                    ("vote_inspector", "can inspect voting"),
                ]
            },
        ),
    ]
