# Generated by Django 3.1.14 on 2022-01-27 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("vote", "0004_votingevent_eligible_group"),
        ("vote", "0005_auto_20210927_0206"),
        ("vote", "0006_votingevent_users_should_poll"),
        ("vote", "0007_auto_20220127_2152"),
    ]

    dependencies = [
        ("vote", "0003_auto_20210210_2135"),
        ("accounts", "0006_auto_20210413_1346"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="votingevent",
            name="eligible_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voting_events",
                to="accounts.nablagroup",
            ),
        ),
        migrations.CreateModel(
            name="BallotContainer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alternative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballots",
                        to="vote.alternative",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="voting",
            name="num_winners",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="BallotEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField()),
                (
                    "alternative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vote.alternative",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="vote.ballotcontainer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ballotcontainer",
            name="voting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ballots",
                to="vote.voting",
            ),
        ),
        migrations.AddField(
            model_name="votingevent",
            name="users_should_poll",
            field=models.BooleanField(
                default=False, verbose_name="Clients should poll for updates"
            ),
        ),
        migrations.AlterField(
            model_name="votingevent",
            name="checked_in_users",
            field=models.ManyToManyField(
                blank=True, related_name="checked_in_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
