# Generated by Django 3.1.14 on 2022-01-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0004_votingevent_eligible_group_squashed_0007_auto_20220127_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingevent",
            name="require_checkin",
            field=models.BooleanField(
                default=True, verbose_name="Users must check in to submit votes"
            ),
        ),
    ]
