# Generated by Django 3.1.13 on 2021-09-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_votingevent_eligible_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_multi_winner',
            field=models.BooleanField(default=False),
        ),
    ]
