# Generated by Django 3.1.13 on 2021-09-26 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_voting_is_multi_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_dict', to='vote.alternative')),
            ],
        ),
        migrations.CreateModel(
            name='PriorityKeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('value', models.IntegerField()),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vote.prioritydict')),
            ],
        ),
    ]
