# Generated by Django 3.1.14 on 2022-02-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0006_auto_20220209_0328"),
        ("vote", "0005_votingevent_require_checkin"),
    ]

    operations = []
