# Generated by Django 3.1.13 on 2021-09-26 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_prioritydict_prioritykeyval'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('count', models.IntegerField()),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vote.prioritydict')),
            ],
        ),
        migrations.DeleteModel(
            name='PriorityKeyVal',
        ),
    ]
