# Generated by Django 3.1.14 on 2022-02-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vote", "0006_auto_20220210_2046"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="is_winner",
            field=models.BooleanField(
                default=False, verbose_name="Alternative is declared winner"
            ),
        ),
    ]
