# Generated by Django 3.1.14 on 2022-02-11 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vote", "0007_voting_is_preference_vote"),
        ("vote", "0007_alternative_is_winner"),
    ]

    operations = []
