# Generated by Django 3.1.13 on 2021-09-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20210926_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='is_multi_winner',
        ),
        migrations.AddField(
            model_name='voting',
            name='num_winners',
            field=models.IntegerField(default=1),
        ),
    ]
