# Generated by Django 3.1.13 on 2021-09-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20210926_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='vote.voting')),
            ],
        ),
        migrations.CreateModel(
            name='BallotEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.alternative')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vote.ballotcontainer')),
            ],
        ),
        migrations.RemoveField(
            model_name='prioritydict',
            name='alternative',
        ),
        migrations.DeleteModel(
            name='PriorityCount',
        ),
        migrations.DeleteModel(
            name='PriorityDict',
        ),
    ]
