# Generated by Django 3.1.14 on 2022-02-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vote", "0009_votingevent_polling_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingevent",
            name="display_description_users",
            field=models.BooleanField(
                default=True, verbose_name="Display the description to users"
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
