# Generated by Django 2.1.13 on 2020-01-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_committee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicationround", name="end",),
        migrations.RemoveField(model_name="applicationround", name="start",),
        migrations.AddField(
            model_name="applicationround",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Er aktiv nå. Kun en opptaksrunde kan være aktiv om gangen.",
            ),
        ),
    ]
