# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0001_squashed_0014_podcast_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="allow_comments",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="content_type",
        ),
    ]
