# Generated by Django 2.1.5 on 2019-03-19 20:47

import django.db.models.deletion
from django.db import migrations, models


"""
def fix_missing_season(apps, schema_editor):
    podcasts = Podcast.objects.all()
    latest_season = Season.objects.last()

    for pod in podcasts:
        try:
            pod.season
        except Season.DoesNotExist:
            pod.season = latest_season
            pod.save()
"""


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0005_auto_20190301_1502"),
    ]

    operations = [
        # migrations.RunPython(fix_missing_season),
        migrations.AlterField(
            model_name="podcast",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="podcast.Season",
                verbose_name="Sesong",
            ),
        ),
    ]
