# Generated by Django 3.0.7 on 2020-11-11 20:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_podcast_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='extra_markdown',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Teksten vil bli kuttet etter 250 tegn på sesongsiden.', verbose_name='beskrivelse'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(default=None, help_text='Bilder som er større enn 300x300 px ser best ut. Du kan beskjære bildet etter opplasting.', upload_to='news_pictures', verbose_name='Bilde'),
            preserve_default=False,
        ),
    ]
