# Generated by Django 3.0.7 on 2020-10-11 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_auto_20200909_1636"),
        ("qrTickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrevent",
            name="nabla_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_event_set",
                to="events.Event",
            ),
        ),
    ]
