# Generated by Django 2.1.9 on 2019-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrTickets', '0002_auto_20190611_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrticket',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
