# Generated by Django 2.1.9 on 2019-06-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrTickets', '0003_qrticket_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_set', to='qrTickets.QrEvent'),
        ),
    ]
