# Generated by Django 2.1.9 on 2019-07-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrTickets', '0004_auto_20190611_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrticket',
            name='id',
        ),
        migrations.AddField(
            model_name='qrticket',
            name='ticket_id',
            field=models.CharField(default=99999, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
