# Generated by Django 2.1.9 on 2019-07-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrTickets', '0005_auto_20190722_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrticket',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrticket',
            name='ticket_id',
            field=models.CharField(default='not valid ticket', max_length=200),
        ),
    ]
