# Generated by Django 2.1.9 on 2019-08-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrTickets', '0006_auto_20190722_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrticket',
            options={'permissions': [('generate_tickets', 'can generate qr tickets'), ('register_tickets', 'can register qr tickets')]},
        ),
    ]
