# Generated by Django 2.1.5 on 2019-02-04 20:57
# Simplified by hiasen

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the


class Migration(migrations.Migration):

    replaces = [('bedpres', '0001_initial'), ('bedpres', '0002_auto_20150925_2315'), ('bedpres', '0003_auto_20171006_1230'), ('bedpres', '0004_move_fields_from_news'), ('bedpres', '0005_news_ptr_to_id_20171006_1559'), ('bedpres', '0006_auto_20171017_0110'), ('bedpres', '0007_remove_bedpres_view_counter')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_squashed_0012_auto_20151106_1921'),
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedPres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, help_text='Brukes på steder hvor det ikke er plass til å skrive hele overskriften, for eksempel kalenderen.', max_length=20, null=True, verbose_name='kort navn')),
                ('organizer', models.CharField(blank=True, help_text='Den som står bak arrangementet', max_length=100, verbose_name='organisert av')),
                ('location', models.CharField(max_length=100, verbose_name='sted')),
                ('event_start', models.DateTimeField(null=True, verbose_name='start')),
                ('event_end', models.DateTimeField(blank=True, null=True, verbose_name='slutt')),
                ('facebook_url', models.CharField(blank=True, help_text='URL-en til det tilsvarende arrangementet på Facebook', max_length=100, verbose_name='facebook-url')),
                ('registration_required', models.BooleanField(default=False, verbose_name='påmelding')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='påmeldingsfrist')),
                ('registration_start', models.DateTimeField(blank=True, null=True, verbose_name='påmelding åpner')),
                ('deregistration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='avmeldingsfrist')),
                ('places', models.PositiveIntegerField(blank=True, null=True, verbose_name='antall plasser')),
                ('has_queue', models.NullBooleanField(help_text='Om ventelisten er på, vil det være mulig å melde seg på selv om arrangementet er fullt. De som er i ventelisten vil automatisk bli påmeldt etter hvert som plasser blir ledige.', verbose_name='har venteliste')),
                ('bpcid', models.CharField(help_text="Dette er id'en som blir brukt internt hos BPC. Ikke endre den hvis du ikke vet hva du gjør.", max_length=16, unique=True, verbose_name='BPC-id')),
                ('company', models.ForeignKey(help_text='Hvilken bedrift som står bak bedriftspresentasjonen', on_delete=django.db.models.deletion.CASCADE, to='jobs.Company', verbose_name='Bedrift')),
                ('open_for', models.ManyToManyField(blank=True, help_text='Hvilke grupper som får lov til å melde seg på arrangementet. Hvis ingen grupper er valgt er det åpent for alle.', to='auth.Group', verbose_name='Åpen for')),
                ('body', models.TextField(blank=True, help_text='Vises kun i artikkelen. Man kan her bruke <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">markdown</a> for å formatere teksten.', verbose_name='brødtekst')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bedpres_created', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publiseringsdato')),
                ('cropping', image_cropping.fields.ImageRatioField('picture', '770x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Beskjæring')),
                ('headline', models.CharField(blank=True, max_length=100, verbose_name='tittel')),
                ('last_changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bedpres_edited', to=settings.AUTH_USER_MODEL, verbose_name='Endret av')),
                ('last_changed_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Redigeringsdato')),
                ('lead_paragraph', models.TextField(blank=True, help_text='Vises på forsiden og i artikkelen', verbose_name='ingress')),
                ('picture', models.ImageField(blank=True, help_text='Bilder som er større enn 770x300 px ser best ut. Du kan beskjære bildet etter opplasting.', null=True, upload_to='uploads/news_pictures', verbose_name='Bilde')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Publikasjonstid')),
                ('published', models.NullBooleanField(default=True, help_text='Dato har høyere prioritet enn dette feltet.', verbose_name='Publisert')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'bedriftspresentasjon',
                'verbose_name_plural': 'bedriftspresentasjoner',
            },
        ),
    ]
