# Generated by Django 2.1.5 on 2019-02-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bedpres', '0001_squashed_0007_remove_bedpres_view_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedpres',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='bedpres',
            name='published',
        ),
    ]
