# Generated by Django 2.1.9 on 2019-10-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bedpres', '0002_auto_20190205_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedpres',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bedpres',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bedpres',
            name='last_changed_by',
        ),
        migrations.RemoveField(
            model_name='bedpres',
            name='open_for',
        ),
        migrations.DeleteModel(
            name='BedPres',
        ),
    ]
