# Generated by Django 2.1.5 on 2019-03-30 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("officeCalendar", "0002_auto_20190325_2028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officeevent",
            name="contact_person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Person of contact",
            ),
        ),
    ]
