# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 02:16
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_auto_20171006_0006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="last_changed_date",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Redigeringsdato",
            ),
        ),
    ]
