# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:07
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import image_cropping.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0005_auto_20171006_0216"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Bilder som er større enn 770x300 px ser best ut. Du kan beskjære bildet etter opplasting.",
                        null=True,
                        upload_to="uploads/news_pictures",
                        verbose_name="Bilde",
                    ),
                ),
                (
                    "cropping",
                    image_cropping.fields.ImageRatioField(
                        "picture",
                        "770x300",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=False,
                        verbose_name="Beskjæring",
                    ),
                ),
                (
                    "view_counter",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Visninger"
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publikasjonstid"
                    ),
                ),
                (
                    "published",
                    models.NullBooleanField(
                        default=True,
                        help_text="Dato har høyere prioritet enn dette feltet.",
                        verbose_name="Publisert",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Publiseringsdato"
                    ),
                ),
                (
                    "last_changed_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Redigeringsdato",
                    ),
                ),
                (
                    "headline",
                    models.CharField(blank=True, max_length=100, verbose_name="tittel"),
                ),
                (
                    "lead_paragraph",
                    models.TextField(
                        blank=True,
                        help_text="Vises på forsiden og i artikkelen",
                        verbose_name="ingress",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text='Vises kun i artikkelen. Man kan her bruke <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">markdown</a> for å formatere teksten.',
                        verbose_name="brødtekst",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsarticle_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opprettet av",
                    ),
                ),
                (
                    "last_changed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsarticle_edited",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Endret av",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
