# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_move_fields_from_news_to_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
