# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:27
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    News = apps.get_model("news", "News")
    for n in News.objects.all():
        n.object_id = n.id
        n.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_object_id'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]

