# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:01
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


def forwards_func(apps, schema_editor):
    News = apps.get_model("news", "News")
    for n in News.objects.all():
        n.bump_time = n.created_date
        n.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_set_object_id_from_news_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-sticky", "-bump_time"),
                "verbose_name": "nyhet",
                "verbose_name_plural": "nyheter",
            },
        ),
        migrations.RemoveField(model_name="news", name="body",),
        migrations.RemoveField(model_name="news", name="created_by",),
        migrations.RemoveField(model_name="news", name="last_changed_by",),
        migrations.RemoveField(model_name="news", name="last_changed_date",),
        migrations.RemoveField(model_name="news", name="publication_date",),
        migrations.RemoveField(model_name="news", name="published",),
        migrations.RemoveField(model_name="news", name="slug",),
        migrations.RemoveField(model_name="news", name="view_counter",),
        migrations.AddField(
            model_name="news",
            name="bump_time",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name="news", name="visible", field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="news", name="sticky", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="content_type",
            field=models.ForeignKey(
                to="contenttypes.ContentType", null=True, on_delete=models.CASCADE
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
