# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_auto_20171006_2201"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="cropping",
            new_name="cropping_override",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="picture",
            new_name="picture_override",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="lead_paragraph",
            new_name="text_override",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="headline",
            new_name="title_override",
        ),
    ]
