# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20171017_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='last_changed_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Redigeringsdato'),
        ),
    ]
