# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20171017_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='FrontPageNews',
        ),
        migrations.AlterModelOptions(
            name='frontpagenews',
            options={'ordering': ('-sticky', '-bump_time'), 'verbose_name': 'Forsidenyhet',
                     'verbose_name_plural': 'Forsidenyheter'},
        ),
        migrations.AlterModelTable(
            name='frontpagenews',
            table=None,
        ),
        migrations.AlterField(
            model_name='frontpagenews',
            name='created_date',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Dette feltet gjør egentlig ingenting. Brukes kun for å se når nyheten ble laget.',
                null=True, verbose_name='Dato laget'),
        ),
        migrations.AlterField(
            model_name='frontpagenews',
            name='picture_override',
            field=models.ImageField(
                blank=True,
                help_text='Bilder som er større enn 770x300 px ser best ut. Du kan beskjære bildet etter opplasting.',
                null=True, upload_to='uploads/frontpageoverride', verbose_name='Bilde'),
        ),
        migrations.AlterField(
            model_name='frontpagenews',
            name='sticky',
            field=models.BooleanField(
                default=False,
                help_text='Blir værende på toppen. Dvs. sorters foran alle andre nyheter.',
                verbose_name='Klebrig'),
        ),
        migrations.AlterField(
            model_name='frontpagenews',
            name='text_override',
            field=models.TextField(blank=True, verbose_name='tekst'),
        ),
        migrations.AlterField(
            model_name='frontpagenews',
            name='visible',
            field=models.BooleanField(
                default=True,
                help_text='Sett dette feltet til usann for å skjule nyheten fra forsiden',
                verbose_name='Er synlig'),
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'Nyhetsartikkel', 'verbose_name_plural': 'Nyhetsartikler'},
        ),
        migrations.AlterField(
            model_name='frontpagenews',
            name='bump_time',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text='Tiden nyheten ble bumpet opp til toppen av forsiden. Brukes som felt for å sortere nyhetene.',
                verbose_name='Sorteringstid'),
        ),
    ]
