# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-22 19:15
from __future__ import unicode_literals

from django.db import migrations

import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_remove_newsarticle_view_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frontpagenews",
            name="cropping_override",
            field=image_cropping.fields.ImageRatioField(
                "picture_override",
                "770x300",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="Beskjæring",
            ),
        ),
    ]
