# Generated by Django 2.1.9 on 2019-09-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20190205_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_ex_news',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
