name: Python linting

on: [push, workflow_dispatch]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort>=5.0
    - name: Check for serious errors with flake8
      run: make check-fatal
    - name: Check formatting with black and isort
      run: make check-formatting

  report-linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint bandit

    - name: Report linting errors with flake8
      run: make report-flake8

    - name: Report linting errors with pylint
      run: make report-pylint

    - name: Report security audit with bandit
      run: make report-bandit
